# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Concom < Formula
  desc "An easy solution to use conventional commits from your command line on any kind of project."
  homepage "https://github.com/Makepad-fr/concom"
  version "0.0.1"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Makepad-fr/concom/releases/download/v0.0.1/concom_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "0a74bdc1ba889467b266c423bdb516d81cadddb688abc00c490f215e94cfb3c2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Makepad-fr/concom/releases/download/v0.0.1/concom_0.0.1_Darwin_arm64.tar.gz"
      sha256 "2c35c38fe5270a805a24aa796ab5f520fcad7b1b0c32649a444b249ce2e75f30"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Makepad-fr/concom/releases/download/v0.0.1/concom_0.0.1_Linux_x86_64.tar.gz"
      sha256 "2815ae1c3f4fa197e4ab55ba189c80e8c85163d8eecad549ad52b986def16952"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Makepad-fr/concom/releases/download/v0.0.1/concom_0.0.1_Linux_arm64.tar.gz"
      sha256 "30d0d0764816c3e885e72e76d3f252bdbeba88a109a527875b314b87f4758c8c"
    end
  end

  def install
    bin.install "concom"
  end
end
